### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jolespin** [cerebis/gfa_io#1]
Has this been tested using Python 3?

Also, does this work for metaSPAdes?

**Comment by cerebis** [comment]
Yes, it should be. At least, when I use this module it is always within a Py3 environment.

The primary effort to switch to Py3 was carried out nearly a year ago.

**Comment by cerebis** [comment]
I just realized I failed to answer the second part of the question.

This is a simple module I wrote originally to assist me in looking at GFAs as graphical objects -- and I wrote it quite a while ago but didn't immediately publish it to github. Then GFA v2 came out, but a lot of programs weren't using it anyhow.

I cannot guarantee its utility for your work, however, I have used this module to read GFAs from a number of sources. Most recently I used it to convert Flye GFAs to SPAdes GFAs, along with the ancillary files SPAdes creates. This was to support another tool which was written around SPAdes.

Please let me know if you have problems.
